app:
  start: Starting Application
  started: Application Started
  req-end: "Request {0} {1} Completed with status {2}. TransactionId: {4}, Timer: {3}"
  req-fail: "Request {0} {1} fail with status {2}, {5}. TransactionId: {4}, Timer: {3}"

short-url:
  cron:
    start: Start Clear Short Url By Expiration
    end: Completed Clear Short Url By Expiration
  error:
    empty-url: empty url
    empty-hash: empty hash
    invalid-url: invalid url
    existent-hash: hash for short url already exists
    not-found: short url not found
    clear-failed: Failed to Clear Short Url By Expiration